Rohan i18nify studio client application
rstudio/rstudio pull request #10099
Opened 2021-11-17 00:53 UTC by rohank07

### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 

This PR tackles hard-coded strings to i18n-ify in i18n-ify org.rstudio.studio.client & .application (excluding false-positives).
Issue: https://github.com/StatCan/daaas/issues/715

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

This pull-request and future ones will tackle i18nify classes at package-level (e.g. org.rstudio.core) instead of the per-component approach (like we did for [all-options-menu](https://github.com/rstudio/rstudio/pull/9599))

Implementation follows the same pattern from #9485 as described in gwt/tools/i18n-helpers/README.md. Running the create_dev_locale.sh will create all the new "dev" locale from any new "en" properties files for easier visual confirmation. Refer to README for more information.
### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

Modify an entry in one of the new _en.properties files, and refresh RStudio with ant in devmode.
Run create_dev_locale.sh to clone all _en properties files, which will add a prefix of "@" to each constant and message. Then open RStudio using http://localhost:8787/?locale=dev and browse to the Options->* menus. You can also view in desktop mode by swapping the locale element value attribute from value="en" to value="dev" in RStudio.gwt.xml.

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

cc @gtritchie

2021-11-17 21:18 UTC, rohank07 commented
Hello @gtritchie, experiencing some build issues with this PR. Encountering issues with classes and subclasses that exist in `/client/application/ui`. I might be missing the source folders in `RStudio.gwt.xml`.  I would appreciate it if you can give me some additional insight. 

![image](https://user-images.githubusercontent.com/28408586/142283669-fbc7982f-046b-44e6-bb72-bbfdbd3d71a4.png)

2021-11-18 22:28 UTC, gtritchie requested changes

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
> +import org.rstudio.studio.client.application.*;
We generally don't use wildcard imports, please revert back to individual ones.

See: "Avoid using wildcard (org.path.to.package.*) imports" on this page: https://github.com/rstudio/rstudio/wiki/Coding-Standards-(java,-cpp)

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
> +   //private final StudioClientApplicationConstants constants_ = GWT.create(StudioClientApplicationConstants.class);
Not used, remove.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
> +import com.google.gwt.core.client.GWT;
Not used, remove

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/Application.java
> +                                                 constants_.quitRunningSessionsMessage() +
Use a single string, not concatenation.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/Application.java
> +                     StringUtil.equals(error.getUserMessage(), constants_.errorTransmissionMessage()))
This code suggests logic that depends on exact string matches. Would need to do deeper review to see if this is a concern here. Leave this comment here so I remember to take another look.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/Application.java
> +                                              constants_.cannotConnectRCaption(),
Single string.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ApplicationInterrupt.java
> +         constants_.terminationDialog() +
Make this a single string.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ApplicationInterrupt.java
> +      constants_.terminationConsequenceMessage() +
Should be a single string.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
> +                  msg + " " + constants_.applicationQuitMessage(),
For flexibility in localization, would run this through a placeholder string, e.g.:

{0} Are you sure you want to quit?

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants.java
> +package org.rstudio.studio.client.application;
Requires our standard file header comment block.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/model/ProductEditionInfo.java
> +      return "RStudio" + (Desktop.isDesktop() ? "" : " " + constants_.rStudioEditionName());
Use string substitution, e.g. "RStudio{0}"

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
> +            constants_.applicationUpdatedMessage() +
Use single string, not three

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
> +            constants_.rSessionErrorCaption(), constants_.previousRSessionsMessage() +
Use single string, not concatenation.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ui/RequestLogDetail.java
> +      html.setText(constants_.requestIdText() + entry.getRequestId() + "\n\n"
This creates a string used for debug diagnostics, don't localize any of this.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ui/RequestLogVisualization.java
> +      instructions_.setHTML("<p>"+ constants_.clickRequestText() +
Debug diagnostics feature, prefer we don't localize this.

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ui/appended/ApplicationEndedPopupPanel.java
> +         constants_.browserDisconnectedMessage() +
Make a single string

2021-11-18 22:28 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/application/ui/appended/ApplicationEndedPopupPanel.java
> +         constants_.rStudioOfflineMessage() +
Make a single string

2021-11-24 00:13 UTC, gtritchie commented
Awesome, I will re-review this and the other PRs tomorrow.

2021-11-25 00:24 UTC, gtritchie approved these changes
Looks good, thanks!

2021-11-25 00:25 UTC, merged