Rohan i18nify org rstudio core
rstudio/rstudio pull request #10090
Opened 2021-11-16 17:21 UTC by rohank07

### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 

This PR tackles hard-coded strings to i18n-ify in org.rstudio.core (excluding false-positives).
Issue: https://github.com/StatCan/daaas/issues/710

I did encounter hard-coded literals that were in Debug.log(). Would these strings be considered as user-facing to i18nify?  I have already i18nify'd them but just wanted to make sure.

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

This pull-request and future ones will tackle i18nify classes at package-level (e.g. org.rstudio.core) instead of the per-component approach (like we did for [all-options-menu](https://github.com/rstudio/rstudio/pull/9599))

Implementation follows the same pattern from #9485 as described in gwt/tools/i18n-helpers/README.md. Running the create_dev_locale.sh will create all the new "dev" locale from any new "en" properties files for easier visual confirmation. Refer to README for more information.
### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

Modify an entry in one of the new _en.properties files, and refresh RStudio with ant in devmode.
Run create_dev_locale.sh to clone all _en properties files, which will add a prefix of "@" to each constant and message. Then open RStudio using http://localhost:8787/?locale=dev and browse to the Options->* menus. You can also view in desktop mode by swapping the locale element value attribute from value="en" to value="dev" in RStudio.gwt.xml.

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

cc @gtritchie

2021-11-18 21:48 UTC, gtritchie requested changes

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
> +         Debug.logWarning(constants_.noFocusableControlsLog());
Debug logging, don't localize.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/NumericValueWidget.java
> +               label_ + " " + constants_.rStudioGinjectorErrorMessage() ,
Use a placeholder in the string, not string concatenation.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/NumericValueWidget.java
> +                  label_ + " " + constants_.rStudioGinjectorGreaterThanError()  + minValue_ + ".",
Use placeholders in the string, not concatenation.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/NumericValueWidget.java
> +                  label_ + " " + constants_.rStudioGinjectorLessThanError() + maxValue_ + ".",
Use placeholders, not concatenation.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java
> +            constants_.operationCompletedText() : labelText_ + " " + constants_.completedText());
Use a placeholder, not concatenation.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/ProgressSpinner.java
> +         Debug.log(constants_.progressSpinnerLog());
Debug logging, don't localize.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
> +         assert existingLabel == null : constants_.existingLabelMessage();
Don't localize asserts.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/ParallelCommandList.java
> +         log(constants_.runningLabel());
Logging, don't localize

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/ParallelCommandList.java
> +            log(constants_.finishedCmdLabel());
Logging, don't localize

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/ParallelCommandList.java
> +            log(constants_.finishedCmdLabel());
Logging, don't localize

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/ParallelCommandList.java
> +      log(constants_.countdownLabel());
Logging, don't localize

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/ParallelCommandList.java
> +         log(constants_.doneLabel());
Logging, don't localize

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/ParallelCommandList.java
> +         Debug.log(hashCode() + " " + label + " " + constants_.logSizeLabel() + commands_.size());
Logging, don't localize

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialog.java
> +            assert false : constants_.navigateIfDirectoryMessage();
Don't localize asserts

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/jsonrpc/RpcRequest.java
> +                        Debug.log(constants_.responseText() + responseText);
Logging, don't localize

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java
> +            constants_.restartRequiredMessage() +
Use a single string here, not two concatenated together.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java
> +              constants_.restartRequiredMessage() +
Use a single string here, not two concatenated together.

2021-11-18 21:48 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/LabeledTextBox.java
> +      textBox_.getElement().setAttribute(constants_.spellCheckAttribute(), enable ? "true" : "false");
Do not localize, this is an HTML attribute name.

2021-11-22 18:18 UTC, rohank07 commented on src/gwt/src/org/rstudio/core/client/ParallelCommandList.java
> +         log(constants_.addCommandLabel());
No, mandate. We are targetting only end user facing UI. I was not sure if this text would be displayed to user.

2021-11-24 23:21 UTC, gtritchie requested changes
Getting close!

2021-11-24 23:21 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
> +import org.rstudio.core.client.*;
Revert the wildcard import back to individual imports.

2021-11-24 23:21 UTC, gtritchie commented on src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java
> +import org.rstudio.core.client.*;
Revert wildcard import back to individual imports.

2021-11-25 00:28 UTC, gtritchie approved these changes
Looks good, thanks!

2021-11-25 00:28 UTC, merged