feat(i18n) workbench-views-source
rstudio/rstudio pull request #10172
Opened 2021-12-02 16:34 UTC by Jose-Matsuda

Implement i18n for classes under workbenc.views.source. This does not include those under views.source.editors.text as those were handled by another PR

### Intent

This PR tackles hard-coded strings to i18n-ify in org.rstudio.studio.client.workbench.views.source (excluding false-positives).
Issue: https://github.com/StatCan/daaas/issues/727

### Approach

This pull-request and future ones will tackle i18nify classes at package-level (e.g. org.rstudio.core) instead of the per-component approach (like we did for all-options-menu)

Implementation follows the same pattern from #9485 as described in gwt/tools/i18n-helpers/README.md. Running the create_dev_locale.sh will create all the new "dev" locale from any new "en" properties files for easier visual confirmation. Refer to README for more information.

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

Modify an entry in one of the new _en.properties files, and refresh RStudio with ant in devmode.
Run create_dev_locale.sh to clone all _en properties files, which will add a prefix of "@" to each constant and message. Then open RStudio using http://localhost:8787/?locale=dev and browse to the Options->* menus. You can also view in desktop mode by swapping the locale element value attribute from value="en" to value="dev" in RStudio.gwt.xml.

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests
- [x] Signed the contributor agreement

cc @gtritchie 

## Please NOTE 
There is a file `ChunkOptionsPopupPanel.java` at `/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java` that I was unsure about adding i18n to so I have marked it with a `TODO` as it seems to be used (in a hardcoded fashion) later in the class / in `SetupChunkOptionsPopupPanel.java`. Just want to know if I need to replace all of those with a constant.

2021-12-02 22:44 UTC, gtritchie requested changes

2021-12-02 22:44 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
> +import com.google.gwt.core.client.*;
Switch back to individual imports, not wildcard.

2021-12-02 22:44 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
> +    private static final ViewsSourceConstants constants_ = GWT.create(ViewsSourceConstants.class);
nitpick: indentation doesn't match

2021-12-02 22:44 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindow.java
> +import com.google.gwt.core.client.*;
Remove wildcard import, put back individual ones

2021-12-02 22:44 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java
> +import com.google.gwt.core.client.*;
revert wildcard import

2021-12-02 22:44 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants.java
> +package org.rstudio.studio.client.workbench.views.source;
Move package line below comment block.

2021-12-02 22:44 UTC, gtritchie commented on src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java
> +      // TODO these 'option's seem to be used later(marked with TODO), do these need translations?
Yes, these are used as you described, and should not be localized. Please remove the TODO comments.

2021-12-07 01:44 UTC, Jose-Matsuda commented
Will address merge conflicts shortly and will push some commits. Will squash into two commits (1st is the initial and 2nd will be the review + conflict merge) and will re-request review when ready

2021-12-07 22:33 UTC, gtritchie approved these changes

2021-12-07 22:33 UTC, merged