revert use of UTF-8 code page on Windows
rstudio/rstudio pull request #10523
Opened 2022-02-07 22:13 UTC by kevinushey

### Intent

Addresses https://github.com/rstudio/rstudio/issues/10507. Either a candidate for a patch release for GO, or for PT.

### Approach

Unfortunately, telling RStudio to use a UTF-8 code page doesn't work as expected with older versions of R, which only support non-UTF-8 code pages. We need to revert that change, and reconsider enabling it for a future release.

### Automated Tests

N/A

### QA Notes

N/A

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

2022-02-07 22:18 UTC, jmcphers requested changes
As this is the first change since the last release of Ghost Orchid, it also needs to bump the patch version from 2 -> 3 here: https://github.com/rstudio/rstudio/blob/fc9e217980ee9320126e33cdf334d4f4e105dc4f/Jenkinsfile#L9https://github.com/rstudio/rstudio/blob/fc9e217980ee9320126e33cdf334d4f4e105dc4f/Jenkinsfile#L9

2022-02-07 22:26 UTC, MariaSemple approved these changes
LGTM!

2022-02-07 22:32 UTC, jmcphers approved these changes

2022-02-07 22:34 UTC, merged

2022-02-07 22:37 UTC, MariaSemple commented
Could add a 2021.09.3 release notes file and add this to it?

2022-02-08 02:26 UTC, kevinushey commented
Thanks! I've updated NEWS: https://github.com/rstudio/rstudio/commit/ab42f62a5f8c126b0611a21edf91c453dace6d34