Full Path on Tab Title When Saving New File on Windows
rstudio/rstudio pull request #11135
Opened 2022-05-05 03:31 UTC by matheustavaresdev

### Intent

Fix an issue that would make the Tab Title show  the full path instead of filename only on windows

### Approach

Removed double slashes for when saving files on Windows.

### Automated Tests

None

### QA Notes

Instructions on #11046

### Checklist

- [X] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [X] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [X] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [X] This PR passes all local unit tests

Addresses ##11046

2022-05-05 16:35 UTC, gtritchie requested changes

2022-05-06 15:43 UTC, matheustavaresdev commented on src/node/desktop/src/renderer/desktop-bridge.ts
> +          if (process.platform == 'win32') {
Alright

2022-05-06 19:34 UTC, kevinushey commented on src/node/desktop/src/renderer/desktop-bridge.ts
> +          if (process.platform == 'win32') {
```suggestion
          if (process.platform === 'win32') {
```

2022-05-06 19:35 UTC, kevinushey approved these changes

2022-05-06 19:35 UTC, merged