i18n: desktop locales
rstudio/rstudio pull request #11324
Opened 2022-05-31 16:49 UTC by rohank07

### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 
Localize desktop specific strings living in C++ Qt code.  
### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ x ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

cc @gtritchie

2022-06-01 07:33 UTC, romainfrancois requested changes
Minor changes. cc @cderv for more :fr: eyes.

2022-06-01 07:33 UTC, romainfrancois commented on src/node/desktop/src/assets/locales/fr.json
> +    "copyImageAddress": "Adresse de l'image à copier",
Does the English mean "address of the image to copy" ? in which case this would be: "Copier l'adresse de l'image"

2022-06-01 07:33 UTC, romainfrancois commented on src/node/desktop/src/assets/locales/fr.json
> +    "rLaunchFailedMessage": "Une erreur s'est produite lors de la tentative de chargement de la version sélectionnée de R. Veuillez sélectionner une installation R différente."
```suggestion
    "rLaunchFailedMessage": "Une erreur s'est produite lors de la tentative de chargement de la version sélectionnée de R. Veuillez sélectionner une installation de R différente."
```

2022-06-01 07:33 UTC, romainfrancois commented on src/node/desktop/src/assets/locales/fr.json
> +    "problemReportCopiedToClipboard": "Rapport de problème copié dans le presse-papiers",
```suggestion
    "problemReportCopiedToClipboard": "Rapport de problème copié dans le presse-papiers.",
```

2022-06-01 07:33 UTC, romainfrancois commented on src/node/desktop/src/assets/locales/fr.json
> +    "rstudioVersion": "Version RStudio",
```suggestion
    "rstudioVersion": "Version de RStudio",
```

2022-06-01 07:33 UTC, romainfrancois commented on src/node/desktop/src/assets/locales/fr.json
> +    "ifPostingThisReportOnlineUseTheCopyProblemReport": "Si vous affichez ce rapport en ligne, utilisez le bouton Copier le rapport de problème ci-dessous pour générer une version textuelle de ce dia
```suggestion
    "ifPostingThisReportOnlineUseTheCopyProblemReport": "Si vous publiez ce rapport en ligne, utilisez le bouton Copier le rapport de problème ci-dessous pour générer une version textuelle de ce diagnostic.",
```

2022-06-01 07:33 UTC, romainfrancois commented on src/node/desktop/src/assets/locales/fr.json
> +    "callbackNyiLowercase": "{{ipcName}} rappel de la NYI"
```suggestion
    "callbackNyiLowercase": "{{ipcName}} rappel pas encore implémenté"
```

2022-06-01 07:33 UTC, romainfrancois commented on src/node/desktop/src/assets/locales/fr.json
> +    "errorLocalizingDocument": "Erreur de localisation du document:"
```suggestion
    "errorLocalizingDocument": "Erreur de localisation du document :"
```

2022-06-01 12:23 UTC, cderv commented on src/node/desktop/src/assets/locales/fr.json
> +    "renderingEngineOptionDesktop": "Espace de travail",
Not sure what english version  "Desktop" really means but using rendering engine "Espace de travail" is not that clear to. 
@romainfrancois you did not flag that so maybe I am just missing some context.

2022-06-01 12:23 UTC, cderv commented on src/node/desktop/src/assets/locales/fr.json
> +    "documentTitle": "Choisir l'installation R",
```suggestion
    "documentTitle": "Choisir l'installation de R",
```

2022-06-02 19:27 UTC, Jose-Matsuda commented
Took the suggestions and made the changes in this PR and in https://github.com/rstudio/rstudio/pull/11325

2022-06-03 21:18 UTC, gtritchie approved these changes

2022-06-03 21:18 UTC, merged