Localize output buffer overload message
rstudio/rstudio pull request #12367
Opened 2022-11-21 20:40 UTC by timtmok

### Intent
Localize the message in the build output when the overload message is displayed.

### Approach
@romainfrancois I ran the string through Google Translate but I doubt that provided a good translation.

### Automated Tests
None

### QA Notes
None

### Checklist

- [x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x] This PR passes all local unit tests

2022-11-22 15:46 UTC, jgutman approved these changes
Pending translation feedback

2022-11-23 14:17 UTC, romainfrancois requested changes

2022-11-23 14:17 UTC, romainfrancois commented on src/gwt/src/org/rstudio/studio/client/common/StudioClientCommonConstants_fr.properties
> +consoleBufferedMessage=\n\n[Débordement de sortie détecté; mettre en mémoire tampon les {0} prochaines lignes de sortie]\n\n
```suggestion
consoleBufferedMessage=\n\n[Débordement de sortie détecté; mise en mémoire tampon des {0} prochaines lignes de sortie]\n\n
```

`Débordement de sortie` still feels odd, but I don't know how I would say it.

2022-11-23 20:00 UTC, timtmok commented
I'll merge for now and see if we get better suggestions later about `Débordement de sortie`.

2022-11-23 20:00 UTC, merged