don't initialize python from restored env null ptr
rstudio/rstudio pull request #13108
Opened 2023-05-10 17:30 UTC by t-kalinowski

closes https://github.com/rstudio/reticulate/issues/710

### Intent

Issue: when a reticulate python object is automatically loaded from a previous R session `.RData` file, the IDE causes reticulate to initialize python while the IDE is generating the object summary for presentation in the env pane.    

### Approach

Add an early return in `rs.describeObject()` that checks for the case of the object being a reticulate null ptr, this avoids running code that otherwise assumes python is already initialized (e.g., `reticulate::import_builtins()`). Reticulate objects loaded from `.RData` will always be null ptrs.

### Automated Tests

NA

### QA Notes

To test locally:

1. create a .RData containing an R object
```r
x = reticulate::py_eval("1", convert = FALSE)
save.image()
``` 
2. Start a fresh R session and restore `.RData`
```r
load(".RData")
if (reticulate::python_available()) 
  stop("Python should not be initialized from merely loading .RData")
```

### Documentation
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate why. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

2023-05-10 17:38 UTC, kevinushey requested changes

2023-05-10 17:38 UTC, kevinushey commented on src/cpp/session/modules/SessionReticulate.R
>     if (reticulate:::py_is_null_xptr(object))
`object` won't be defined here; do we need to check if `parent` itself is a null external pointer?

2023-05-10 17:52 UTC, t-kalinowski commented
Reading through the rest of `rs.reticulate.describeObject()`, it looks like `builtins` are never used, so a simpler fix is to just remove the `import_builtins()` line. Updated the PR.

2023-05-11 04:27 UTC, kevinushey approved these changes
LGTM, thanks!

2023-05-11 04:27 UTC, merged