Resumable busy sections
rstudio/rstudio pull request #15055
Opened 2024-08-15 20:10 UTC by maximsmol

### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 

Fixes #15053 

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

Handle workbench initialization requests on the connection listener thread if the main thread is busy. Return latest available information for session state that requires running R code to be determined.

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Documentation
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate why. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [X] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

2024-08-19 16:23 UTC, gtritchie commented
Thanks for your contribution! We'll try and get this reviewed soon.

In the meantime, have you filled out the contributor agreement per the instructions here? https://github.com/rstudio/rstudio/blob/main/CONTRIBUTING.md#contributing-code

2024-08-20 14:50 UTC, ronblum commented
@gtritchie  Is this going into main, and hence Kousa Dogwood?

2024-08-20 14:56 UTC, gtritchie commented
> @gtritchie Is this going into main, and hence Kousa Dogwood?

Yes, it is targeted to main:

<img width="390" alt="merge target main" src="https://github.com/user-attachments/assets/c51e6798-9df8-47ce-9318-bc9321e8679e">

2024-08-23 20:28 UTC, gtritchie commented
@maximsmol sorry for delay in getting this reviewed; we haven't forgotten. In the meantime do you mind syncing your fork with upstream rstudio `main` and resolving the merge conflicts that github is identifying? That'll make it easier to merge when the time comes.

2024-08-23 22:36 UTC, maximsmol commented
no worries, we're testing more internally for now

the conflict is just some includes - will patch soon

2024-09-06 23:29 UTC, maximsmol commented
just noting that the merge conflict was resolved, let me know if anything else looks off at a glance

2024-09-27 02:53 UTC, jeffvroom requested changes
Thank you for this amazing contribution. So sorry for the long delay in the review. 

I have a few things that I think will make this better/more reliable. I'm happy to make these changes based on this branch to take it the last mile, but if you are motivated I can walk you through the changes as well. 

You've really done the heavy lifting here, so kudos and congrats. It might take some time to make sure this is reliable enough. As a stop-gap, we can make it opt-in to get it in sooner as I'm sure it will be much appreciated by users.

1. I think rather than running handleClientInit in the connection listener thread, it should be done in the [offline thread](https://github.com/rstudio/rstudio/blob/7c3cbb05a8007a673af39b68d6e05540089ba03e/src/cpp/session/SessionOfflineService.cpp#L255C79-L255C103). That will add a small delay, but will avoid weird behavior for when the R runtime is busy for a brief moment when you happen to join. This offline thread is where operations like save-file and other thread-safe/main-thread-aware operations are handled now when R is busy. It polls the connection queue looking for "offlineable requests" and runs them. Since it's only activated after the first client_init, no need to add that test. I believe it can just be [added to the offlineable URIs](https://github.com/rstudio/rstudio/blob/7c3cbb05a8007a673af39b68d6e05540089ba03e/src/cpp/session/SessionRpc.cpp#L388-L403) and all the code in the http connection listener can be removed.  Then handleClientInit will only be called when R is busy, if it's already been initialized, and enough time has passed.

2. Instead of testing console::executing() I think we should be testing: !core::thread::isMainThread().  There's no situation where we want to be running R code on another thread. The executing state can change from line-to-line so it's not a guarantee that we are not on the right thread. 

3. The change to Application.java needs some extra review, especially for desktop. That code change avoids the set_user_prefs RPC (I can see why you removed it since it's not offlineable, whereas set_user_state is). It was added when we added the tab layout to user preferences so there must be some interaction where, where in some situations you need to update the user preferences, like when the window size changes or something. We probably need a way to identify when they have actually changed and only send them in that case, or maybe make set_user_prefs offlineable?  Not a big deal, especially if it turns out it's only a desktop thing. I just need to sync up with the developer who wrote that and make sure we handle that case. 

4. Review of all the new cached values... will they be accurate? The best way to handle this is to update the cached value after we know it might have changed, like in a package install hook, or some other hook that's run periodically. If it will never change, what you have is fine.  We've had to do this before for other state to make more code work in the offline thread but it's going to take some time.

5. We'd like to also run the handleClientInit in the debugger in this situation, with breakpoints set in some low-level R hooks. While we've added some "isMainThread" checks, they are not free and so lower level R utils might be running happily "most of the time" and there's a relatively easy way to check that.  

 Let me know if you'd like me to take over on this, if I missed anything or you have questions/concerns about the comments. Thanks again for the great contribution!

2024-09-28 18:01 UTC, maximsmol commented
Thanks for getting back to me! I appreciate the kind words!

I'll try to make some of the changes you requested, although I don't have a very good grasp on some things (see notes below) so it might take a few iterations and a bunch of time. I'm not super aware of your release schedule so let me know if a deadline is coming up.

Also, if you ever feel like taking over, please do! My only interest is helping get this stuff merged quickly and with least effort on your part.

---

1. Agreed. I was not aware that the "offlineable" thread existed. I'll make this change

2. Agreed, will make this change

3. I'll look into it but I'm not sure if I'll be able to test it thoroughly. The comment in `Application.java` ("refresh prefs incase they were loaded without sessionInfo") is a bit cryptic and I've never used the desktop version. It might also take me some time to figure out how to build it. I'd appreciate it if you could get the original author to comment on this part

4. My reasoning for not deliberately updating the cached values was that in the case you never reload the page you'd be seeing stale values anyway so we just get back to that on reload now (which I hand-waved as a "strict improvement"). I also think most values I cached are only read once on `client_init` which would mean that the client never gets updated values anyway, but I might have just missed it. I agree that a proper audit to find all the appropriate refresh hooks/triggers would be ideal, but I am very very new to R runtime code so I am not confident doing this on my own

5. Correct me if I'm wrong, you are saying that we should double-check that no other main-thread-only R code is running from `handleClientInit`? I would need guidance on where to put the breakpoints

2024-11-06 18:24 UTC, gtritchie commented
Unfortunately we haven't been able to get this landed for the Kousa Dogwood (2024.11), and we're essentially out of time, so moving this to the next release.

2025-02-13 19:04 UTC, closed without merging

2025-02-13 19:04 UTC, gtritchie commented
Sorry it sat so long, but I don't see us getting this change into the product, so am closing this PR.