Add overlay methods to handle session CRAN repo defaults
rstudio/rstudio pull request #15364
Opened 2024-10-25 03:35 UTC by skyeturriff

### Intent

> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related. 

### Approach

> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's complicated.

### Automated Tests

> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, indicate why.

### QA Notes

> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked issues. 

### Documentation
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate why. 

### Checklist

- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ ] This PR passes all local unit tests

2024-10-25 15:11 UTC, gtritchie approved these changes
LGTM!

2024-10-25 16:00 UTC, gtritchie requested changes
Just noticed there's no NEWS entry. It should mention that both Server Pro and Desktop Pro are impacted by this.

2024-11-05 16:08 UTC, gtritchie commented on NEWS.md
> +- Set Public Package Manager (P3M) as the default for R libraries in RStudio Pro sessions, if no other repository is specified. Package Manager will deliver pre-built binary packages when available,
Caveat: perhaps our branding has changed to refer to "RStudio Server Pro" as just "RStudio Pro." In which case, ignore my comment.

2024-11-05 16:12 UTC, skyeturriff commented on NEWS.md
> +- Set Public Package Manager (P3M) as the default for R libraries in RStudio Pro sessions, if no other repository is specified. Package Manager will deliver pre-built binary packages when available,
Oh! I was meaning to reference the RStudio Pro sessions in Workbench, like here:

![Screenshot 2024-11-05 at 11 11 27 AM](https://github.com/user-attachments/assets/2e12661e-1e44-4c00-975c-08315769460f)

2024-11-05 17:35 UTC, gtritchie commented on NEWS.md
> +- Set Public Package Manager (P3M) as the default for R libraries in RStudio Pro sessions, if no other repository is specified. Package Manager will deliver pre-built binary packages when available,
Okay, given that I'd leave it the way you have it.

2024-11-09 00:44 UTC, merged