OS PR for https://github.com/rstudio/rstudio-pro/pull/7254
rstudio/rstudio pull request #15559
Opened 2024-12-27 22:36 UTC by GCRev

Also made previous entries consistent for verb tense.

2024-12-27 23:54 UTC, gtritchie approved these changes
LGTM!

2025-01-02 18:15 UTC, gtritchie requested changes
This PR is targeting the `main` branch, it should target `rel-kousa-dogwood`.

2025-01-06 17:02 UTC, GCRev commented
@gtritchie done.

2025-01-06 17:04 UTC, gtritchie approved these changes

2025-01-06 17:04 UTC, merged