companion commit for rstudio/rstudio-pro#2030
rstudio/rstudio pull request #7970
Opened 2020-10-05 19:53 UTC by ricardofandrade

2020-10-05 23:05 UTC, jmcphers requested changes

2020-10-05 23:05 UTC, jmcphers commented on NEWS.md
> +* **DEPRECATED:** The option `auth-proxy-require-hmac` is no longer operational and a warning will be issued to the logs if used. See the documentation on proxy authentication for alternatives. (Pro
Nit: let's not lead with this as the very first thing people read about what we've done in this release! (put it towards the end of the notes)

2020-10-07 14:43 UTC, ricardofandrade commented on NEWS.md
> +* **DEPRECATED:** The option `auth-proxy-require-hmac` is no longer operational and a warning will be issued to the logs if used. See the documentation on proxy authentication for alternatives. (Pro
```suggestion
* **REMOVED:** The option `auth-proxy-require-hmac` is no longer operational and RStudio will not run if present. See the documentation on [Proxied Authentication] for alternatives to secure RStudio. (Pro #2029)
```

2020-10-08 13:39 UTC, ricardofandrade commented on NEWS.md
> +* **REMOVED:** The option `auth-proxy-require-hmac` is no longer operational and RStudio will not run if present. See the documentation on [Proxied Authentication] for alternatives to secure RStudio.
```suggestion
* **REMOVED:** The option `auth-proxy-require-hmac` is no longer operational and RStudio will not run if present. See the documentation on [Proxy Security Considerations] for alternatives to secure RStudio. (Pro #2029)
```

2020-10-12 16:03 UTC, ricardofandrade commented on NEWS.md
> +* **REMOVED:** The option `auth-proxy-require-hmac` is no longer operational and RStudio will not run if present. See the documentation on [Proxy Security Considerations] for alternatives to secure R
```suggestion
* **RETIRED:** The option `auth-proxy-require-hmac` is has been retired and it is no longer operational. RStudio will not start if enabled. See the documentation on [Proxy Security Considerations] for alternatives to secure RStudio. (Pro #2029)
```

2020-10-12 16:04 UTC, merged